name: "Build Status Action"

description: "Returns build result"

outputs:
  result:
    description: "Build result"
    

runs:
  using: "composite"

  steps:
    - name: Set Output
      id: custom-action
      uses:./.github/actions/java-build


    - name: Print Output
      run: echo "${{ steps.custom-action.outputs.result }}"